#                                                                        #
# Default subroutes configuration for the FLOW3 package                  #
#                                                                        #

# $Id$

##
# Default route to the FLOW3 Authentication Controller

-
  name: 'Authentication with action'
  uriPattern: 'flow3/authentication/{@action}'
  defaults:
    '@package':    'TYPO3.FLOW3'
    '@subpackage': 'Security\Authentication'
    '@controller': 'Authentication'

-
  name: 'Authentication'
  uriPattern: 'flow3/authentication'
  defaults:
    '@package':    'TYPO3.FLOW3'
    '@subpackage': 'Security\Authentication'
    '@controller': 'Authentication'
    '@action':     'authenticate'


##
# Default route to map the first three URL segments to package, controller and action
# including optional format-suffix

-
  name: 'default with action and format'
  uriPattern: '{@package}/{@controller}/{@action}(.{@format})'
  defaults:
    '@format':     'html'
  appendExceedingArguments: true

##
# Default route to map the first two URL segments to package and controller
# optional third URL segment is mapped to action

-
  name: 'default'
  uriPattern: '{@package}/{@controller}(/{@action})'
  defaults:
    '@action':     'index'
    '@format':     'html'
  appendExceedingArguments: true

##
# Default route with just the package

-
  name: 'default with package'
  uriPattern: '{@package}'
  defaults:
    '@controller': 'Standard'
    '@action':     'index'
    '@format':     'html'
  appendExceedingArguments: true

##
# Fallback route

-
  name: 'fallback'
  uriPattern: ''
  defaults:
    '@package':    'TYPO3.FLOW3'
    '@subpackage': 'Mvc'
    '@controller': 'Standard'
    '@action':     'index'
    '@format':     'html'
