#                                                                        #
# Default subroutes configuration for the FLOW3 package                  #
#                                                                        #

# $Id$

##
# Default route to the FLOW3 Login Controller

--
  name: 'Login with action'
  uriPattern: 'flow3/login/{@action}'
  defaults:
    @package:    'FLOW3'
    @subpackage: 'Security'
    @controller: 'Login'

--
  name: 'Login'
  uriPattern: 'flow3/login'
  defaults:
    @package:    'FLOW3'
    @subpackage: 'Security'
    @controller: 'Login'
    @action:     'index'
    

##
# Default route to map the first three URL segments to package, controller and action 
# including optional format-suffix

--
  name: 'default with action and format'
  uriPattern: '{@package}/{@controller}/{@action}(.{@format})'
  defaults:
    @format:     'html'

##
# Default route to map the first two URL segments to package and controller
# optional third URL segment is mapped to action

--
  name: 'default'
  uriPattern: '{@package}/{@controller}(/{@action})'
  defaults:
    @action:     'index'
    @format:     'html'

##
# Default route with just the package

--
  name: 'default with package'
  uriPattern: '{@package}'
  defaults:
    @controller: 'Standard'
    @action:     'index'
    @format:     'html'

##
# Fallback route

--
  name: 'fallback'
  uriPattern: ''
  defaults:
    @package:    'FLOW3'
    @subpackage: 'MVC'
    @controller: 'Standard'
    @action:     'index'
    @format:     'html'
