#                                                                        #
# Example Settings                                                       #
#                                                                        #
# This file contains settings for various parts of the application.      #
# Copy this file to Settings.yaml, and adjust as necessary.              #
#                                                                        #
# Please refer to the default settings file(s) or the manuals for        #
# possible configuration options.                                        #
#                                                                        #

TYPO3:
  FLOW3:
    persistence:
      backendOptions:
        dbname: 'flow3_functional_testing'
