Neos:
 RedirectHandler:
  features:
    hitCounter: true
  statusCode:
    'redirect': 307
    'gone': 410

TYPO3:
  Flow:
    http:
      chain:
        'process':
          chain:
            'redirect':
              position: 'after routing'
              component: 'Neos\RedirectHandler\RedirectComponent'
