#                                                                        #
# Configuration for the FLOW3 Framework                                  #
#                                                                        #
# This file contains additions to the base configuration for the FLOW3   #
# Framework when it runs in Development context.                         #
#                                                                        #
# Don't modify this file - instead put your own additions into the       #
# global Configuration directory and its sub directories.                #
#                                                                        #

FLOW3:
  configuration:
    compileConfigurationFiles: n

  error:
    exceptionHandler:
      className: 'F3\FLOW3\Error\DebugExceptionHandler'
    errorHandler:
      exceptionalErrors: [%E_USER_ERROR%, %E_RECOVERABLE_ERROR%, %E_WARNING%, %E_NOTICE%, %E_USER_WARNING%, %E_USER_NOTICE%, %E_STRICT%]

  monitor:
    detectClassChanges: y

  resource:
    publishing:
      detectPackageResourceChanges: y

  log:
    systemLogger:
      backendOptions: { logFileURL: %FLOW3_PATH_DATA%Logs/%FLOW3_SAPITYPE%/FLOW3_Development.log, createParentDirectories: y, severityThreshold: %LOG_DEBUG% }
