#                                                                        #
# Configuration for the TYPO3 Flow Framework                             #
#                                                                        #
# This file contains additions to the base configuration for the TYPO3   #
# Flow Framework when it runs in Testing context.                        #
#                                                                        #
# Don't modify this file - instead put your own additions into the       #
# global Configuration directory and its sub directories.                #
#                                                                        #

TYPO3:

  Flow:

    core:
      subRequestEnvironmentVariables:
        XDEBUG_CONFIG: 'idekey=FLOW_SUBREQUEST remote_port=9001'

    error:
      exceptionHandler:
        className: 'TYPO3\Flow\Error\DebugExceptionHandler'
      errorHandler:
        exceptionalErrors: ['%E_USER_ERROR%', '%E_RECOVERABLE_ERROR%', '%E_WARNING%', '%E_NOTICE%', '%E_USER_WARNING%', '%E_USER_NOTICE%', '%E_STRICT%']

    log:
      systemLogger:
        backendOptions:
          logFileURL: '%FLOW_PATH_DATA%Logs/System_Testing.log'
          severityThreshold: '%LOG_DEBUG%'
      securityLogger:
        backendOptions:
          logFileURL: '%FLOW_PATH_DATA%Logs/Security_Testing.log'
          severityThreshold: '%LOG_DEBUG%'
      sqlLogger:
        backendOptions:
          logFileURL: '%FLOW_PATH_DATA%Logs/Query_Testing.log'
          severityThreshold: '%LOG_DEBUG%'

    object:
      registerFunctionalTestClasses: true

    persistence:
      backendOptions:
        driver: 'pdo_sqlite'
        path: ':memory:'
        username: NULL
        password: NULL
      doctrine:
        cacheImplementation: NULL

        eventSubscribers:
          'TYPO3\Flow\Tests\Functional\Persistence\Fixtures\EventSubscriber':
            'TYPO3\Flow\Tests\Functional\Persistence\Fixtures\EventSubscriber'
        eventListeners:
          'TYPO3\Flow\Tests\Functional\Persistence\Fixtures\EventListener':
            events: ['onFlush', 'preFlush', 'postFlush']
            listener: 'TYPO3\Flow\Tests\Functional\Persistence\Fixtures\EventListener'

    resource:

      # Definition of resource storages provided by the Flow core.
      # Storages are used for storing and retrieving resources.
      storages:

        #
        defaultPersistentResourcesStorage:
          storage: 'TYPO3\Flow\Resource\Storage\WritableFileSystemStorage'
          storageOptions:
            path: '%FLOW_PATH_DATA%Persistent/TestResources/'

        #
        defaultStaticResourcesStorage:
          storage: 'TYPO3\Flow\Resource\Storage\PackageStorage'

      # Definition of the default resource collections.
      # Collections are used to bundle / group static or persistent resources
      # for common processing and publication.
      collections:

        # Collection which contains all static resources
        static:
          storage: 'defaultStaticResourcesStorage'
          target: 'localWebDirectoryStaticResourcesTarget'
          pathPatterns:
            - '*/Resources/Public/*'

        # Collection which contains all persistent resources
        persistent:
          storage: 'defaultPersistentResourcesStorage'
          target: 'localWebDirectoryPersistentResourcesTarget'

      # Definition of the basic resource publication targets.
      targets:
        # Target for publishing static resources to the local web directory
        localWebDirectoryStaticResourcesTarget:
          target: 'TYPO3\Flow\Resource\Target\FileSystemSymlinkTarget'
          targetOptions:
            path: '%FLOW_PATH_WEB%_Resources/Testing/Static/Packages/'
            baseUri: '_Resources/Testing/Static/Packages/'

        # Target for publishing persistent resources to the local web directory
        localWebDirectoryPersistentResourcesTarget:
          target: 'TYPO3\Flow\Resource\Target\FileSystemSymlinkTarget'
          targetOptions:
            path: '%FLOW_PATH_WEB%_Resources/Testing/Persistent/'
            baseUri: '_Resources/Testing/Persistent/'
            # If the generated URI path segment containing the sha1 should be divided into multiple segments (recommended if you expect many resources):
            subdivideHashPathSegment: false

    security:
      authentication:
        authenticationStrategy: anyToken

        providers:
          TestingProvider:
            provider: 'TYPO3\Flow\Security\Authentication\Provider\TestingProvider'
            entryPoint: 'WebRedirect'
            entryPointOptions:
              uri: 'flow/authentication'
            requestPatterns:
              controllerObjectName: 'TYPO3\Flow\Tests\.*'
          HttpBasicTestingProvider:
            provider: 'TYPO3\Flow\Security\Authentication\Provider\PersistedUsernamePasswordProvider'
            token: 'TYPO3\Flow\Security\Authentication\Token\UsernamePasswordHttpBasic'
            requestPatterns:
              controllerObjectName: 'TYPO3\Flow\Tests\Functional\Security\Fixtures\Controller\HttpBasicTestController'
          UsernamePasswordTestingProvider:
            provider: 'TYPO3\Flow\Security\Authentication\Provider\PersistedUsernamePasswordProvider'
            token: 'TYPO3\Flow\Security\Authentication\Token\UsernamePassword'
            requestPatterns:
              controllerObjectName: 'TYPO3\Flow\Tests\Functional\Security\Fixtures\Controller\UsernamePasswordTestController'

    # Setting for functional tests to test global objects in runtime evaluations
    aop:
      globalObjects:
        testContext: 'TYPO3\Flow\Tests\Functional\Aop\Fixtures\TestContext'

    # Settings for functional tests to test setting designator and setting injection
    tests:
      functional:
        aop:
          pointcutExpressionSettingFilterOptionA: true
        dependencyInjection:
          singletonConstructorArgument: 'setting injected singleton value'
          prototypeConstructorArgument: 'setting injected property value'
        settingInjection:
          someSetting: 'injected setting'
