#                                                                        #
# Configuration for the TYPO3 Flow Framework                             #
#                                                                        #
# This file contains additions to the base configuration for the TYPO3   #
# Flow Framework when it runs in Testing context.                        #
#                                                                        #
# Don't modify this file - instead put your own additions into the       #
# global Configuration directory and its sub directories.                #
#                                                                        #

TYPO3:

  Flow:

    configuration:
      compileConfigurationFiles: FALSE

    core:
      subRequestEnvironmentVariables:
        XDEBUG_CONFIG: 'idekey=FLOW_SUBREQUEST remote_port=9001'

    error:
      exceptionHandler:
        className: 'TYPO3\Flow\Error\DebugExceptionHandler'
      errorHandler:
        exceptionalErrors: ['%E_USER_ERROR%', '%E_RECOVERABLE_ERROR%', '%E_WARNING%', '%E_NOTICE%', '%E_USER_WARNING%', '%E_USER_NOTICE%', '%E_STRICT%']

    log:
      systemLogger:
        backendOptions:
          logFileURL: '%FLOW_PATH_DATA%Logs/System_Testing.log'
          severityThreshold: '%LOG_DEBUG%'
      securityLogger:
        backendOptions:
          logFileURL: '%FLOW_PATH_DATA%Logs/Security_Testing.log'
          severityThreshold: '%LOG_DEBUG%'
      sqlLogger:
        backendOptions:
          logFileURL: '%FLOW_PATH_DATA%Logs/Query_Testing.log'
          severityThreshold: '%LOG_DEBUG%'

    object:
      registerFunctionalTestClasses: true

    persistence:
      backendOptions:
        driver: 'pdo_sqlite'
        path: ':memory:'
        username: NULL
        password: NULL

      doctrine:
        eventSubscribers:
          - 'TYPO3\Flow\Tests\Functional\Persistence\Fixtures\EventSubscriber'
        eventListeners:
          -
            events: ['onFlush', 'preFlush', 'postFlush']
            listener: 'TYPO3\Flow\Tests\Functional\Persistence\Fixtures\EventListener'

    security:
      authentication:
        authenticationStrategy: anyToken

        providers:
          TestingProvider:
            provider: 'TYPO3\Flow\Security\Authentication\Provider\TestingProvider'
            entryPoint: 'WebRedirect'
            entryPointOptions:
              uri: 'flow/authentication'
            requestPatterns:
              controllerObjectName: 'TYPO3\Flow\Tests\.*'
          HttpBasicTestingProvider:
            provider: 'TYPO3\Flow\Security\Authentication\Provider\PersistedUsernamePasswordProvider'
            token: 'TYPO3\Flow\Security\Authentication\Token\UsernamePasswordHttpBasic'
            requestPatterns:
              controllerObjectName: 'TYPO3\Flow\Tests\Functional\Security\Fixtures\Controller\HttpBasicTestController'
          UsernamePasswordTestingProvider:
            provider: 'TYPO3\Flow\Security\Authentication\Provider\PersistedUsernamePasswordProvider'
            token: 'TYPO3\Flow\Security\Authentication\Token\UsernamePassword'
            requestPatterns:
              controllerObjectName: 'TYPO3\Flow\Tests\Functional\Security\Fixtures\Controller\UsernamePasswordTestController'

    # Setting for functional tests to test global objects in runtime evaluations
    aop:
      globalObjects:
        testContext: 'TYPO3\Flow\Tests\Functional\Aop\Fixtures\TestContext'

    # Settings for functional tests to test setting designator and setting injection
    tests:
      functional:
        aop:
          pointcutExpressionSettingFilterOptionA: true
        dependencyInjection:
          singletonConstructorArgument: 'setting injected singleton value'
          prototypeConstructorArgument: 'setting injected property value'
        settingInjection:
          someSetting: 'injected setting'
